apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
spec:
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=/workspace/source/app/shopping-web/Dockerfile"
        - "--context=/workspace/source/app/shopping-web"
        - "--destination=<your-registry>/shopping-web:latest"
