apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-update-gitops
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build-image
      taskRef:
        name: build-image
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: update-kustomize
      runAfter: [build-image]
      taskRef:
        name: update-kustomize
      workspaces:
        - name: source
          workspace: shared-workspace
