apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-web
  labels:
    app: shopping-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-web
  template:
    metadata:
      labels:
        app: shopping-web
    spec:
      imagePullSecrets:
        - name: nhncloud-registry-secret
      containers:
        - name: shopping-web
          image: shopping-web  # 이미지는 kustomization.yaml에서 설정
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 10
