resources:
- deployment.yaml
- service.yaml
images:
- name: shopping-web
  newName: ec175433-kr1-registry.container.nhncloud.com/pub-real-kr1/shopping-web
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
