apiVersion: v1
kind: Service
metadata:
  name: shopping-web
  labels:
    app: shopping-web
spec:
  selector:
    app: shopping-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: LoadBalancer
